name: BeaconWars
main: com.github.calfur.beaconWars.Main
version: 2.0.0
api-version: 1.17
depend: [DeathBan]
softdepend: [VillagerSaver, sleep-most]
description: You can find a plugin documentation inside of the readme file on https://github.com/Calfur/BeaconWars
author: Robin Nater alias Calfur
website: www.github.com/Calfur/BeaconWars
commands:
  collect:
    description: Gibt dem Spieler die Gewuenschte Anzahl Items aus seinem Belohnungsguthaben
    usage: /<command> Itemname Anzahl
  player:
    description: Interagiert mit der Spielerdatenbank
    usage: /<command> [add | edit | info | delete | list] Spielername Teamnummer RealName
  team:
    description: Interagiert mit der Teamdatenbank
    usage: /<command> [add | edit | info | delete | list] Teamnummer Farbe Beacon_x Beacon_y Beacon_z TeamLeader
  playerkill:
    description: Interagiert mit der Killdatenbank
    usage: /<command> [add | info | delete | list] [id | page] [Killer] [Opfer] [Grund]
  beaconfight:
    description: Zum hinzufuegen oder loeschen von Becon Events
    usage: /<command> [add | delete] [DateTime (yyyy-MM-dd_HH:mm)] [Eventduration (Minutes)] [Attackduration (Minutes)]
    permission: admin
  buildmode:
    description: Aktiviert oder Deaktiviert den Baumodus
    usage: /<command>
  projectStart:
    description: Aktiviert oder Deaktiviert den Projektstart Zustand
    usage: /<command>
    permission: admin
  startProjectForPlayers:
    description: Teleportiert Spieler zu ihrem Teambeacon und setzt sie in den Startzustand (Effekte, Hunger, Spawnpoint)
    usage: /<command> [Spieler]
    permission: admin
  totemcooldown:
    description: Gibt die verbleibende cooldown Zeit zurueck
    usage: /<command> [Spieler]
  namenametag:
    description: Benennt nametags welche in der Main-Hand gehalten werden
    usage: /<command> Name
  compass:
    description: Erhalte einen Kompass mit dem ausgewaehlten Ziel
    usage: /<command> [Base | Spawn | Beacon] [TeamId]
  transaction: 
    description: Interagiert mit der Transaktionsdatenbank
    usage: /<command> [info | list | add | reverse] [Id | page | diamonds | points] [amount] [player] [reason]
  reloadConfig:
    description: Reload the Configurations based on the config.yml file
    usage: /<command>
    permission: admin
permissions:
  admin:
    description: Erlaubt das benutzen von allen BeaconWars commands
    default: op