name: DiamondKill
main: com.github.calfur.minecraftserverplugins.diamondkill.Main
version: 1.0
api-version: 1.13
commands:
  collect:
    description: Gibt dem Spieler die Gewuenschte Anzahl Items aus seinem Belohnungsguthaben
    usage: /<command> Itemname Anzahl
  player:
    description: Interagiert mit der Spielerdatenbank
    usage: /<command> [add | edit | info | delete] Teamnummer Discordname
    permission: admin
  team:
    description: Interagiert mit der Teamdatenbank
    usage: /<command> [add | edit | info]
permissions:
  admin:
    description: Erlaubt das benutzen von DiamondKill commands
    default: op
