name: DiamondKill
main: com.github.calfur.minecraftserverplugins.diamondkill.Main
version: 1.0
api-version: 1.13
commands:
  collect:
    description: Gibt dem Spieler die Gewuenschte Anzahl Items aus seinem Belohnungsguthaben
    usage: /<command> Itemname Anzahl
  player:
    description: Interagiert mit der Spielerdatenbank
    usage: /<command> [add | edit | info | delete | list] Spielername Teamnummer Discordname
  team:
    description: Interagiert mit der Teamdatenbank
    usage: /<command> [add | edit | info | delete | list] Teamnummer Farbe Beacon_x Beacon_y Beacon_z 
  playerkill:
    description: Interagiert mit der Killdatenbank
    usage: /<command> [add | edit | info | delete | list] [Id] Killer Opfer
  beaconfight:
    description: Interagiert mit der Killdatenbank
    usage: /<command> [add | delete] [DateTime (yyyy-MM-dd_HH:mm)]
  buildmode:
    aliases: 
    - pengin
    description: Aktiviert oder Deaktiviert den Baumodus
    usage: /<command>
permissions:
  admin:
    description: Erlaubt das benutzen von allen DiamondKill commands
    default: op