name: DiamondKill
main: com.github.calfur.minecraftserverplugins.diamondkill.Main
version: 1.1.1
api-version: 1.16
depend: [DeathBan]
description: You can find a plugin documentation inside of the readme file on https://github.com/Calfur/BeaconWars
author: Robin Nater
commands:
  collect:
    description: Gibt dem Spieler die Gewuenschte Anzahl Items aus seinem Belohnungsguthaben
    usage: /<command> Itemname Anzahl
  player:
    description: Interagiert mit der Spielerdatenbank
    usage: /<command> [add | edit | info | delete | list] Spielername Teamnummer RealName
  team:
    description: Interagiert mit der Teamdatenbank
    usage: /<command> [add | edit | info | delete | list] Teamnummer Farbe Beacon_x Beacon_y Beacon_z TeamLeader
  playerkill:
    description: Interagiert mit der Killdatenbank
    usage: /<command> [add | info | delete | list] [Id] [Killer] [Opfer] [Grund]
  beaconfight:
    description: Zum hinzufuegen oder loeschen von Becon Events
    usage: /<command> [add | delete] [DateTime (yyyy-MM-dd_HH:mm)] [Eventduration (Minutes)] [Attackduration (Minutes)]
  buildmode:
    aliases:
    - baumodus
    description: Aktiviert oder Deaktiviert den Baumodus
    usage: /<command>
  projectStart:
    description: Aktiviert oder Deaktiviert den Projektstart Zustand
    usage: /<command>
  startProjectForPlayers:
    description: Teleportiert Spieler zu ihrem Teambeacon und setzt sie in den Startzustand (Effekte, Hunger, Spawnpoint)
    usage: /<command> [Spieler]
  totemcooldown:
    description: Gibt die verbleibende cooldown Zeit zurueck
    usage: /<command> [Spieler]
  namenametag:
    description: Benennt nametags welche in der Main-Hand gehalten werden
    usage: /<command> Name
  compass:
    description: Erhalte einen Kompass mit dem ausgewaehlten Ziel
    usage: /<command> [Base | Spawn | Beacon] [TeamId]
  transaction: 
    description: Interagiert mit der Transaktionsdatenbank
    usage: /<command> [info | list] [Id]
permissions:
  admin:
    description: Erlaubt das benutzen von allen DiamondKill commands
    default: op