name: DiamondKill
main: com.github.calfur.minecraftserverplugins.diamondkill.Main
version: 1.0
api-version: 1.13
commands:
  collect:
    description: Gibt dem Spieler die Gewuenschte Anzahl Items aus seinem Belohnungsguthaben
    usage: /<command> Itemname Anzahl
  player:
    description: Registriert einen neuen Spieler in der Datenbank
    usage: /<command> [add | edit | info | delete] Teamnummer Discordname
permissions:
  admin:
    description: Erlaubt das benutzen von DiamondKill commands
    default: op
